### ISSUE TITLE
Angular 19

### ISSUE THREAD

**Issue by achapman009** [daemons88/ngx-custom-material-file-input#1]
There is a breaking change when trying to upgrade to version 19 of angular.

![image](https://github.com/user-attachments/assets/2aae4967-3245-49ca-83e0-2bfa4c4870be)

Is there plans to upgrade this project past 18?

Thanks.

**Comment by daemons88** [comment]
Yes, probably at the end of the next month or sooner I'll be starting the migration.

And if you have the time to lend a hand to review what the possible changes would be, it would be faster to make the migration.

**Comment by daemons88** [comment]
Finished the migration to Angular 19, additionally, I added some new features, you can take a look [here](https://github.com/daemons88/ngx-custom-material-file-input/releases/tag/19.0.0).
